# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 9/26/2023, 4:18:06 PM
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("TeamsAppSetupPolicy", "TeamsCallQueue", "TeamsChannel", "TeamsChannelsPolicy", "TeamsChannelTab", "TeamsMessagingPolicy", "TeamsOnlineVoiceUser", "TeamsOrgWideAppSettings", "TeamsTeam", "TeamsUser", "TeamsUserCallingSettings") -Credential $Credential